services:
  webserver:
    build: .
    image: webserver
    container_name: webserver
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./docker/webserver/etc/apache2/sites-enabled/
        target: /etc/apache2/sites-enabled/
    environment:
      APACHE_LOG_DIR: /var/log/apache2
      XDEBUG_MODE: debug
      XDEBUG_SESSION: 1
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.37-bookworm
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3333:3306"
  
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
    - mysql
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: lucas-sandery
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
    - 8888:8080
volumes:
  db-data:
